name: groupchat
description: 群聊
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.4
  path_provider: ^1.3.0
  dio: ^3.0.7
  event_bus: ^1.1.0
  #缓存
  shared_preferences: ^0.5.6
  synchronized: '>=2.0.2 <4.0.0'
  flutter_easyloading: ^1.1.3
  fluttertoast: ^3.1.3
  web_socket_channel: ^1.1.0
  cached_network_image: ^2.0.0-rc
  flutter_swiper: ^1.1.6
  photo_view: ^0.7.0
  url_launcher: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/leimu/
    - images/girl/
    - images/jiaoxiao/

